<a href="https://colab.research.google.com/github/kwangwonland/kfq_ML_2023/blob/main/0615_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%2C%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn

In [ ]:
print(sklearn.__version__)

1.2.2


# 첫 번째 머신러닝-붓꽃 품종 예측하기

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

In [ ]:
iris=load_iris()
print(iris)

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris_data=iris.data
iris_data.shape

(150, 4)

In [ ]:
iris_label=iris.target

In [ ]:
np.unique(iris_label,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [ ]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df

In [ ]:
xa=[[x,x] for x in range(100)]
ya=[y for y in range(100)]
x_train,x_test,y_train,y_test=train_test_split(xa,ya)

In [ ]:
for i in range(len(x_train)):
    print(x_train[i],':',y_train[i])


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(iris_data,iris_label,test_size=0.2)

In [ ]:
model=DecisionTreeClassifier() #모델 생성
model.fit(x_train,y_train) #모델 학습

DecisionTreeClassifier()

In [ ]:
pred=model.predict(x_test)

In [ ]:
for i in range(len(pred)):
    print(pred[i],':',y_test[i])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred) # 모델 평가

0.9666666666666667

# 프레임워크 익히기

In [ ]:
iris_data=load_iris()

In [ ]:
keys=iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# Model Selection 모듈 소개

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np


In [ ]:
iris = load_iris()
features = iris.data
label = iris.target


In [ ]:
dt_clf = DecisionTreeClassifier() #모델 생성
kfold = KFold(n_splits=5)
cv_accuracy =[]
n_iter = 0


In [ ]:
iris=load_iris()
feature=iris.data
label=iris.target

In [ ]:
for train_ind, test_ind in kfold.split(features):
    x_train,x_test = features[train_ind], features[test_ind]
    y_train,y_test = label[train_ind], label[test_ind]

    dt_clf.fit(x_train,y_train) #학습
    pred = dt_clf.predict(x_test) #예측
    n_iter+=1

    acc = np.round(accuracy_score(pred,y_test),3)
    print(n_iter,"회 교차 검증 accuracy:",acc)
    cv_accuracy.append(acc)
print("평균 accuracy:",np.mean(cv_accuracy))


2 회 교차 검증 accuracy: 1.0
3 회 교차 검증 accuracy: 1.0
4 회 교차 검증 accuracy: 0.9
5 회 교차 검증 accuracy: 0.933
6 회 교차 검증 accuracy: 0.733
평균 accuracy: 0.9132


In [ ]:
iris = load_iris()
iris_df = pd.DataFrame(iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()


0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_ind,test_ind in kfold.split(iris_df):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_ind]
    label_test = iris_df['label'].iloc[test_ind]
    print("##",n_iter,"회 교차 검증")
    print("학습 데이터 분포\n",label_train.value_counts())
    print("평가 데이터 분포\n",label_test.value_counts())


## 1 회 교차 검증
학습 데이터 분포
 1    50
2    50
Name: label, dtype: int64
평가 데이터 분포
 0    50
Name: label, dtype: int64
## 2 회 교차 검증
학습 데이터 분포
 0    50
2    50
Name: label, dtype: int64
평가 데이터 분포
 1    50
Name: label, dtype: int64
## 3 회 교차 검증
학습 데이터 분포
 0    50
1    50
Name: label, dtype: int64
평가 데이터 분포
 2    50
Name: label, dtype: int64


In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
dt_clf = DecisionTreeClassifier() #모델 생성
skf = StratifiedKFold(n_splits=3)
cv_accuracy =[]
n_iter = 0
for train_ind, test_ind in skf.split(features,label):
    x_train,x_test = features[train_ind], features[test_ind]
    y_train,y_test = label[train_ind], label[test_ind]

    dt_clf.fit(x_train,y_train) #학습
    pred = dt_clf.predict(x_test) #예측
    n_iter+=1

    acc = np.round(accuracy_score(pred,y_test),3)
    print(n_iter,"회 교차 검증 accuracy:",acc)
    cv_accuracy.append(acc)
print("평균 accuracy:",np.mean(cv_accuracy))


1 회 교차 검증 accuracy: 0.98
2 회 교차 검증 accuracy: 0.94
3 회 교차 검증 accuracy: 0.98
평균 accuracy: 0.9666666666666667


In [51]:
from sklearn.model_selection import cross_val_score, cross_validate

In [53]:
data=iris.data
label=iris.target
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [55]:
dt=DecisionTreeClassifier()
scores=cross_val_score(dt,data,label,scoring='accuracy',cv=3)
print("교차 검증 accuracy:",np.round(scores,4))
print("평균 검증 accuracy:",np.round(np.mean(scores),4))


교차 검증 accuracy: [0.98 0.92 0.98]
평균 검증 accuracy: 0.96


In [57]:
dt=DecisionTreeClassifier()
scores=cross_validate(dt,data,label,scoring='accuracy',cv=3)
scores

{'fit_time': array([0.01098561, 0.00128818, 0.0011127 ]),
 'score_time': array([0.01210594, 0.00536609, 0.00310707]),
 'test_score': array([0.98, 0.92, 0.96])}

In [59]:
x_train, x_test, y_train,y_test = train_test_split(iris_data.data,iris_data.target, test_size=0.2)

In [60]:
mds=[1,2,3]
for depth in mds:
    dt=DecisionTreeClassifier(max_depth=depth)
    dt.fit(x_train,y_train)
    pred=dt.predict(x_test)
    print(depth,':acc',accuracy_score(y_test,pred))

1 :acc 0.6333333333333333
2 :acc 0.9333333333333333
3 :acc 0.9


In [61]:
mds = [1,2,3]
mss = [2,3,4]
for depth in mds:
  for ms in mss:
    dt = DecisionTreeClassifier(max_depth=depth,min_samples_split=ms)
    dt.fit(x_train,y_train)
    pred = dt.predict(x_test)
    print(depth,",",ms,": acc =",accuracy_score(y_test,pred))

1 , 2 : acc = 0.6333333333333333
1 , 3 : acc = 0.6333333333333333
1 , 4 : acc = 0.6333333333333333
2 , 2 : acc = 0.9333333333333333
2 , 3 : acc = 0.9333333333333333
2 , 4 : acc = 0.9333333333333333
3 , 2 : acc = 0.9
3 , 3 : acc = 0.9
3 , 4 : acc = 0.9


In [62]:
from sklearn.model_selection import GridSearchCV


In [63]:
iris_data = load_iris()
x_train, x_test, y_train,y_test = train_test_split(
    iris_data.data,iris_data.target, test_size=0.2)


In [65]:
grid_parameters = {'max_depth':[1,2,3],
                  'min_samples_split':[2,3]}
dtree = DecisionTreeClassifier() #모델 생성
grid_dtree = GridSearchCV(dtree,param_grid=grid_parameters,cv=3,refit=True)
grid_dtree.fit(x_train,y_train) #학습


GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [66]:
print("최적 파라미터:",grid_dtree.best_params_)
print("최고 accuracy:",grid_dtree.best_score_)


최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
최고 accuracy: 0.9833333333333334


In [67]:
estimator = grid_dtree.best_estimator_
pred = estimator.predict(x_test)
print("테스트 accuracy:",accuracy_score(y_test,pred))


테스트 accuracy: 0.9666666666666667


# 데이터 전처리
## LabelEncoder,OnehotEncoder

In [68]:
from sklearn.preprocessing import LabelEncoder

In [69]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [70]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)


In [71]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [74]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
items = np.array(items).reshape(-1,1)
encoder = OneHotEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels.toarray()


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [77]:
items

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [78]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
pd.get_dummies(items)


TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [82]:
heights = stats.norm.rvs(loc=173,scale=4,size=1000)
bmis = stats.norm.rvs(loc=21,scale=2,size=1000)
weights = bmis*(heights**2)/10000

In [83]:
c_sizes = [ (heights[i]*2+weights[i]*2)/5  for i in range(1000)]
c_sizes = np.array(c_sizes)

In [84]:
from sklearn.neighbors import KNeighborsRegressor
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values

In [87]:
label=c_sizes

In [88]:
x_train,x_test,y_train,y_test=train_test_split(data,label)

In [92]:
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9970224400100387

In [95]:
iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)

In [96]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [97]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [98]:
sl = iris_df['sepal length (cm)']
v = sl.var()
v2 = (v*149)/150
st = np.sqrt(v2)
scaled = (sl-sl.mean())/st
scaled[:5]


0   -0.900681
1   -1.143017
2   -1.385353
3   -1.506521
4   -1.021849
Name: sepal length (cm), dtype: float64

In [99]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
scaled = scaler.transform(iris_df)
df2 = pd.DataFrame(scaled)
df2.head(5)

0         1         2         3
0 -0.900681  1.019004 -1.340227 -1.315444
1 -1.143017 -0.131979 -1.340227 -1.315444
2 -1.385353  0.328414 -1.397064 -1.315444
3 -1.506521  0.098217 -1.283389 -1.315444
4 -1.021849  1.249201 -1.340227 -1.315444

In [102]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
scaled = scaler.transform(iris_df)
df2 = pd.DataFrame(scaled)
df2.head(5)

0         1         2         3
0  0.222222  0.625000  0.067797  0.041667
1  0.166667  0.416667  0.067797  0.041667
2  0.111111  0.500000  0.050847  0.041667
3  0.083333  0.458333  0.084746  0.041667
4  0.194444  0.666667  0.067797  0.041667

In [103]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9943246085139803

In [105]:
x_train, x_test, y_train, y_test = train_test_split(data,label)
x_train

array([[177.49610397,  76.37337516],
       [166.98722279,  54.00676207],
       [178.38233368,  70.86749848],
       ...,
       [177.40033922,  59.10997776],
       [173.82382721,  61.02707053],
       [171.96411282,  77.53587112]])

In [107]:
mms1=MinMaxScaler()
mms1.fit(x_train)
scaled_train=mms1.transform(x_train)

mms2=MinMaxScaler()
mms2.fit(x_test)
scaled_test=mms2.transform(x_test)

sample=[[175,89],[172,62]]

In [108]:
mms1.transform(sample)

array([[0.62642951, 1.17805623],
       [0.50261461, 0.53034806]])

In [109]:
mms2.transform(sample)

array([[0.585015  , 0.97185324],
       [0.44360127, 0.41545035]])